sudo: required
dist: xenial
language: cpp
osx_image: xcode10.1

os:
#  - linux # Whenever travis starts keeping up to date we can use this again.
  - osx

compiler:
  - gcc

script:
  - cd Test
  - ruby RootTest.rb

notifications:
  email:
    recipients:
      - contact@blacktoppstudios.com
    on_success: change
    on_failure: always
