sudo: required
dist: xenial
language: cpp
osx_image: xcode10.1

os:
  - osx

script:
  - cd Test
  - ruby RootTest.rb

notifications:
  email:
    recipients:
      - contact@blacktoppstudios.com
    on_success: change
    on_failure: always
