version: 0.0.{build}
clone_folder: C:\projects\Jagati

image:
  - Visual Studio 2017

build_script:
  - cd Test
  - ruby RootTest.rb
  
notifications:
- provider: Email
  to:
  - contact@blacktoppstudios.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
